/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings` (hash: 9112b18a12a19214d8c08361a1cc9596)
interface __BaseEnv_WorkerBindings {
	SUMMARIES: KVNamespace;
	ASSETS: Fetcher;
	GEMINI_MODEL: "gemini-3.1-flash-lite";
	END_TO_END_TIMEOUT_MS: "60000";
	DAILY_SUMMARY_LIMIT: "300";
	FREE_USER_MONTHLY_LIMIT: "5";
	FREE_GLOBAL_MONTHLY_LIMIT: "50";
	APP_PASSWORD: string;
	GEMINI_API_KEY: string;
	TRANSCRIPTAPI_API_KEY: string;
	GENERATION_QUOTA: DurableObjectNamespace<import("./src/worker").GenerationQuota>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "GenerationQuota";
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_MODEL" | "END_TO_END_TIMEOUT_MS" | "DAILY_SUMMARY_LIMIT" | "FREE_USER_MONTHLY_LIMIT" | "FREE_GLOBAL_MONTHLY_LIMIT" | "APP_PASSWORD" | "GEMINI_API_KEY" | "TRANSCRIPTAPI_API_KEY">> {}
}
