/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings` (hash: 864439db2a0cc19d315e125403d5dff0)
interface __BaseEnv_WorkerBindings {
	SUMMARIES: KVNamespace;
	ASSETS: Fetcher;
	GEMINI_MODEL: "gemini-3.1-flash-lite";
	END_TO_END_TIMEOUT_MS: "15000";
	DAILY_SUMMARY_LIMIT: "300";
	APP_PASSWORD: string;
	GEMINI_API_KEY: string;
	TRANSCRIPTAPI_API_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GEMINI_MODEL" | "END_TO_END_TIMEOUT_MS" | "DAILY_SUMMARY_LIMIT" | "APP_PASSWORD" | "GEMINI_API_KEY" | "TRANSCRIPTAPI_API_KEY">> {}
}
