import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const wrangler = path.resolve('node_modules', 'wrangler', 'bin', 'wrangler.js');
const checking = process.argv.includes('--check');
const useGeneratedComparison = checking && process.platform === 'win32';
const temporaryDirectory = useGeneratedComparison
  ? mkdtempSync(path.join(os.tmpdir(), 'nbs-worker-types-'))
  : undefined;
const outputPath = temporaryDirectory
  ? path.join(temporaryDirectory, 'worker-configuration.d.ts')
  : undefined;
const args = [
  wrangler,
  'types',
  ...(outputPath ? [outputPath] : []),
  '--env-interface',
  'WorkerBindings',
  '--include-runtime',
  'false',
  ...(checking && !useGeneratedComparison ? ['--check'] : []),
];

const result = spawnSync(process.execPath, args, {
  stdio: useGeneratedComparison ? 'pipe' : 'inherit',
  encoding: useGeneratedComparison ? 'utf8' : undefined,
  env: {
    ...process.env,
    CLOUDFLARE_LOAD_DEV_VARS_FROM_DOT_ENV: 'false',
    WRANGLER_LOG_PATH: path.resolve('.wrangler', 'wrangler.log'),
  },
});

let exitCode = result.status ?? 1;
if (useGeneratedComparison) {
  try {
    if (exitCode !== 0) {
      process.stdout.write(result.stdout ?? '');
      process.stderr.write(result.stderr ?? '');
    } else {
      const committed = normalizeLineEndings(readFileSync('worker-configuration.d.ts', 'utf8'));
      const generated = normalizeLineEndings(readFileSync(outputPath, 'utf8'));
      if (committed !== generated) {
        console.error('Worker binding types are out of date. Run `npm run types:sync`.');
        exitCode = 1;
      } else {
        console.log('Worker binding types are up to date.');
      }
    }
  } finally {
    rmSync(temporaryDirectory, { recursive: true, force: true });
  }
}

process.exitCode = exitCode;

function normalizeLineEndings(value) {
  return value.replace(/\r\n?/gu, '\n').replace(/^\/\/ Generated by Wrangler[^\n]*\n/mu, '');
}
