import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const wrangler = path.resolve('node_modules', 'wrangler', 'bin', 'wrangler.js');
const checking = process.argv.includes('--check');
const useWindowsGenerator = process.platform === 'win32';
const comparisonPath = useWindowsGenerator
  ? path.resolve(`.worker-configuration.windows-check-${process.pid}.d.ts`)
  : undefined;
const args = [
  wrangler,
  'types',
  ...(comparisonPath ? [comparisonPath] : []),
  '--env-interface',
  'WorkerBindings',
  '--include-runtime',
  'false',
  ...(checking && !useWindowsGenerator ? ['--check'] : []),
];

const result = spawnSync(process.execPath, args, {
  stdio: useWindowsGenerator ? 'pipe' : 'inherit',
  encoding: useWindowsGenerator ? 'utf8' : undefined,
  env: {
    ...process.env,
    CLOUDFLARE_LOAD_DEV_VARS_FROM_DOT_ENV: 'false',
    WRANGLER_LOG_PATH: path.resolve('.wrangler', 'wrangler.log'),
  },
});

let exitCode = result.status ?? 1;
if (useWindowsGenerator) {
  try {
    if (exitCode !== 0) {
      process.stdout.write(result.stdout ?? '');
      process.stderr.write(result.stderr ?? '');
    } else {
      const generated = canonicalizeWindowsTypes(readFileSync(comparisonPath, 'utf8'));
      if (checking) {
        const committed = normalizeLineEndings(readFileSync('worker-configuration.d.ts', 'utf8'));
        if (committed !== generated) {
          console.error('Worker binding types are out of date. Run `npm run types:sync`.');
          exitCode = 1;
        } else {
          console.log('Worker binding types are up to date.');
        }
      } else {
        writeFileSync('worker-configuration.d.ts', generated);
        console.log('Types written to worker-configuration.d.ts.');
      }
    }
  } finally {
    rmSync(comparisonPath, { force: true });
  }
}

process.exitCode = exitCode;

// Wrangler currently misses re-export metadata on Windows, so restore the same
// Durable Object types that the canonical Linux generator emits.
function canonicalizeWindowsTypes(value) {
  const normalized = normalizeLineEndings(value);
  const bodyStart = normalized.indexOf('interface __BaseEnv_WorkerBindings');
  if (bodyStart < 0) throw new Error('Wrangler generated an unexpected bindings file.');

  let body = normalized
    .slice(bodyStart)
    .replace(
      'DurableObjectNamespace /* GenerationQuota */',
      'DurableObjectNamespace<import("./src/worker").GenerationQuota>',
    );
  if (!body.includes('\tinterface GlobalProps {')) {
    body = body.replace(
      'declare namespace Cloudflare {\n',
      'declare namespace Cloudflare {\n\tinterface GlobalProps {\n\t\tmainModule: typeof import("./src/worker");\n\t\tdurableNamespaces: "GenerationQuota";\n\t}\n',
    );
  }
  const hash = createHash('sha256').update(body).digest('hex').slice(0, 32);
  return `/* eslint-disable */\n// Generated by Wrangler by running \`wrangler types --include-runtime=false --env-interface=WorkerBindings\` (hash: ${hash})\n${body}`;
}

function normalizeLineEndings(value) {
  return value.replace(/\r\n?/gu, '\n');
}
